### PR TITLE
Add benchmark for https://github.com/YasserAsmi/jvar

### PR DESCRIPTION
**Pull request by YasserAsmi**
I have written the test module for jvar.  However, I didn't figure out how to insert a link for the library itself like you have for other libs.  The lib can be found at https://github.com/YasserAsmi/jvar  and it should go into thirdparty/jvar.  Thanks

### CODE REVIEW

**Comment by miloyip** [comment]
You can try at the project root:
~~~
git submodule add https://github.com/YasserAsmi/jvar.git thirdparty/jvar
~~~
And then add the change to this PR.

**Comment by YasserAsmi** [comment]
OK done--thanks

**Comment by miloyip** [comment]
@YasserAsmi , I just found out that jvar cannot compile on VC2015, due to

~~~
1>c:\github\nativejson-benchmark\thirdparty\jvar\include\util.h(406): error C3861: 'gmtime_r': identifier not found
1>c:\github\nativejson-benchmark\thirdparty\jvar\include\util.h(412): error C3861: 'time': identifier not found
1>c:\github\nativejson-benchmark\thirdparty\jvar\include\util.h(413): error C3861: 'localtime_r': identifier not found
1>c:\github\nativejson-benchmark\thirdparty\jvar\include\util.h(421): error C3861: 'mktime': identifier not found
1>c:\github\nativejson-benchmark\thirdparty\jvar\include\util.h(427): error C3861: 'strftime': identifier not found
1>c:\github\nativejson-benchmark\thirdparty\jvar\include\util.h(432): error C3861: 'strptime': identifier not found
1>c:\github\nativejson-benchmark\thirdparty\jvar\include\util.h(442): error C3861: 'timegm': identifier not found
1>c:\github\nativejson-benchmark\thirdparty\jvar\include\util.h(448): error C3861: 'difftime': identifier not found
1>c:\github\nativejson-benchmark\thirdparty\jvar\include\util.h(453): error C3861: 'difftime': identifier not found
1>c:\github\nativejson-benchmark\thirdparty\jvar\include\util.h(478): error C3861: 'usleep': identifier not found
...
~~~

I just checked the latest version seems to have the same problem. Will you check that?
I will temporarily disable the compilation of the test on VC temporarily.

**Comment by YasserAsmi** [comment]
@miloyip Sure I will check the VC2015

**Pull request merged**
